server:
  port: 8888

spring:
  application:
    name: chatroom
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chatroom?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver